### ISSUE TITLE
ECS resource detector crash

### ISSUE THREAD

**Issue by bonclay7** [aws-observability/aws-otel-go#16] opened 2021-01-28 17:41 UTC
Hello ! 

This is similar to https://github.com/aws-observability/aws-otel-go/issues/11. Using the ecs detector like this:

```go
ecsResourceDetector := new(ecs.ResourceDetector)
resource, err := ecsResourceDetector.Detect(ctx)

if err != nil {
	fmt.Println("ECS Resource detection error:", err)
}
```

So, running on EC2 returns an error as expected, ` process is not on ECS, cannot detect environment variables from ECS`. 
However on ECS, there is no error, and the application crash with the following logs

![image](https://user-images.githubusercontent.com/10175027/106177038-4e35bd00-6198-11eb-9a64-548658ef4ca2.png)

**Comment by bhautikpip** [comment] 2021-02-05 00:37
Hi @bonclay7 ,

Thanks for opening an issue. I tried to take a look at this issue. From the logs you posted I think the you're receiving an error when detector is trying to get host name (https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/detectors/aws/ecs/ecs.go#L72). I also submitted a pull request to add error message in this scenario as well (https://github.com/open-telemetry/opentelemetry-go-contrib/pull/568). Ideally from the code looks like even if resource detector is not able to find `container name` or `container id` it should return empty resource and not crashing. Are you still experiencing this issue? If yes, would you provide detailed repro steps so that I can reproduce on my end for better debugging and see what's going on.

**Comment by bonclay7** [comment] 2021-02-08 19:16
Hi ! Tried the Fix above and it's working fine. Can't wait for the next release

https://github.com/open-telemetry/opentelemetry-go-contrib/pull/569#issuecomment-775377620

**Comment by bhautikpip** [comment] 2021-02-24 00:19
This fix is rolled out in recent release - https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v0.17.0 so closing this issue. Feel free to open new one if the issue still exists!

**Closed by bhautikpip** 2021-02-24 00:19 UTC
